name: Run Scraper

on:
  workflow_dispatch:
    inputs:
      payload:
        description: "JSON input from Power Automate"
        required: true

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper with input
        run: python scraper.py '${{ github.event.inputs.payload }}'

      - name: Upload Excel result
        uses: actions/upload-artifact@v3
        with:
          name: rezultat
          path: output.xlsx
